### ISSUE TITLE
Might want to use .format() instead 

### ISSUE THREAD

**Issue by Sail338** [11/plogs#7]
https://github.com/11/plogs/blob/c721991ab296021bd1698f6a48418f49c16f8bd8/src/plogutils.py#L112

**Comment by 11** [comment]
made a similar change:         
https://github.com/11/plogs/blob/8b76f1c869d3d809b6d5dc0597bf230f512e4203/src/plogutils.py#L96

**Comment by 11** [comment]
if you `pip install --update plogs`, v0.1.5 will have this fix
